### PR TITLE
Switch to bindgen-generated bindings

### LINKED ISSUE #11: Moving to bindgen-generated bindings?
I see you wrote bindings (`csound-sys`) manually. Is there any particular reason for that? Can it be replaced by the bindgen generated bindings?

### PR DESCRIPTION
**Pull request by ales-tsurko**
Closes #11 

Switch to bindgen to generate raw bindings. 

Bindings are now generated at build time, that's because there could be platform-dependent defines.

### CODE REVIEW

**Comment by ales-tsurko** [comment]
@neithanmo could you review it?

**Comment by neithanmo** [comment]
> @neithanmo could you review it?

Hi @ales-tsurko  It looks awesome. Have not finished yet.. but on it. Maybe tomorrow I would finish and publish to crates.io with version 2.0..thinking of tagging it as version 1.9 though.

**Comment by neithanmo** [comment]
I am gettings some errors compiling this.
```

error[E0308]: mismatched types
  --> src/callbacks.rs:54:53
   |
54 |         raw::csoundSetMessageStringCallback(csound, Some(Trampoline::message_string_cb))
   |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found enum `Option`
   |
   = note: expected fn pointer `extern "C" fn(*mut CSOUND, i32, *const i8)`
                    found enum `Option<extern "C" fn(*mut CSOUND, i32, *const i8) {message_string_cb}>`

error[E0599]: no associated item named `CSOUND_CHANNEL_TYPE_MASK` found for type `u32` in the current scope
```

or :
```

error[E0599]: no associated item named `CSOUND_CHANNEL_TYPE_MASK` found for type `u32` in the current scope
   --> src/callbacks.rs:547:67
    |
547 |             let channel_type = channel_type & controlChannelType::CSOUND_CHANNEL_TYPE_MASK as i32;
    |                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `u32`
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `CSOUND_CHANNEL_TYPE_MASK`, perhaps you need to implement one of them:
            candidate #1: `<ControlChannelType as Debug>::fmt::__BitFlags`
            candidate #2: `ControlChannelType::all::__BitFlags`
```
taking a look

**Comment by ales-tsurko** [comment]
Looks like you use the previous version of `csound-sys`. Have you changed it in `Cargo.toml`?

**Comment by neithanmo** [comment]
> Looks like you use the previous version of `csound-sys`. Have you changed it in `Cargo.toml`?

yes.. Forgot that.
I noticed the the csound/ folder is empty. what is your intention here? using it as a git-submodule pinned to the latest released version of csound?? if that the case I think we should include something like:
```

    if !Path::new("curl/.git").exists() {
        let _ = Command::new("git")
            .args(&["submodule", "update", "--init"])
            .status();
    }
```
It fails to compile because it does not find the `csound.h` file. Or I am doing something wrong..maybe

**Comment by ales-tsurko** [comment]
AFAIK, git submodules fetched automatically by Cargo. For manual usage you can initialize it normally:

```
git submodule init
git submodule update
```

Or use `--recursive` when you clone the repo.

UPD It looks like cargo actually packages everything from the environment it has. But without submodules being initialized CD/CI anyway wouldn't work (and code wouldn't compile), so it's hard to misuse. And using submodules the usual way (`git submodule` init/update or `git clone --recursive ...`) is the way to go. Moreover, the submodule was here before this PR (and I updated it in the previous one).

**Comment by ales-tsurko** [comment]
> ```
> 
>     if !Path::new("curl/.git").exists() {
>         let _ = Command::new("git")
>             .args(&["submodule", "update", "--init"])
>             .status();
>     }
> ```

This won't work for `csound-sys`, because the submodule is for `csound-rs` repo. So when the script will run for `csound-sys` on its own, it won't know about the submodule. In overall, it's expected when you use git, that you initialize submodules manually (or clone recursively). A note in README.md about it would be helpful for contributors, though.

**Comment by neithanmo** [comment]
> This won't work for `csound-sys`, because the submodule is for `csound-rs` repo. So when the script will run for `csound-sys` on its own, it won't know about the submodule. In overall, it's expected when you use git, that you initialize submodules manually (or clone recursively). A note in README.md about it would be helpful for contributors, though.

I think the submodule is for csound-sys, and the build script will take care of updating and initializing it. once done the compilation of csound-rs build work without issues.  We can move the .gitsubmodule from csound-rs/ to csound-sys/ 
as they do in curl.  and make this automatically done. Can you try this?? 
Do you think we should add a feature to allow users to use their local `csound.h` ?

**Comment by ales-tsurko** [comment]
I'm absolutely sure, you don't need to include submodules fetching in the crate's build script, as it's a git submodule - it should be managed on the git level. It's supposed that when you build it locally (i.e. you're a developer) you already initialized the submodules. When you'll package `csound-sys`, you'll also have all the files included, otherwise it just won't build - so it's impossible to misuse. This is a normal way to go with git submodules.

> Do you think we should add a feature to allow users to use their local csound.h ?

That's a bad idea as the user's version could be different from one, to which `csound-rs` is linked.

**Comment by neithanmo** [comment]
> I'm absolutely sure, you don't need to include submodules fetching in the crate's build script, as it's a git submodule - it should be managed on the git level. It's supposed that when you build it locally (i.e. you're a developer) you already initialized the submodules. When you'll package `csound-sys`, you'll also have all the files included, otherwise it just won't build - so it's impossible to misuse. This is a normal way to go with git submodules.

Makes sense. But another thing is that users might pull this from the repository, in that case, they would need to pull for the git-submodule manually in order to compile csound-rs, which would be awkward. So that, somehow, This encourages people to pull this crate from crates.io directly.

> 
> > Do you think we should add a feature to allow users to use their local csound.h ?
> 
> That's a bad idea as the user's version could be different from one, to which `csound-rs` is linked.

Yes, You are right.

**Comment by ales-tsurko** [comment]
> in that case, they would need to pull for the git-submodule manually in order to compile csound-rs, which would be awkward.

Having git submodules is a usual thing for a git repo. Normally, those who know how to use git are familiar with git submodules as well. Also, I added a note to the README.md that the repo has submodules.

**Comment by ales-tsurko** [comment]
Anyway, if you wish to have submodules initialization in the build.rs, why you just don't merge the PR and add it yourself? The PR doesn't have any blocking changes, which prevent you to do this.

**Pull request merged**
